branch-defaults:
  default:
    environment: bs-index12
environment-defaults:
  bs-index12:
    branch: null
    repository: null
global:
  application_name: bs_index1
  default_ec2_keyname: alex-nx
  default_platform: python-3.6
  default_region: cn-northwest-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
